repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v22.1.8
    hooks:
      - id: clang-format
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.23.1
    hooks:
      - id: markdownlint-cli2-docker
  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint-docker
